[profile.default]
src = "src"
out = "out"

libs = ["lib", ".venv/lib/python3.12/site-packages"]

skip = ["**/snekmate/**/*[!c][!k].vy", "**/snekmate/**/*.vyi"] # Skip the compilation of non-mock and interface files.
evm_version="cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[vyper]
path = ".venv/bin/vyper"