[profile.default]
src = "src"
out = "out"

libs = ["lib", "dependencies"]

skip = ["**/snekmate/**/*[!c][!k].vy", "**/snekmate/**/*.vyi"] # Skip the compilation of non-mock and interface files.
evm_version="cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[vyper]
path = ".venv/bin/vyper"

[fmt]
bracket_spacing = true

[dependencies]
forge-std = "1.9.4"
